### ISSUE TITLE
gateway 에서의 토큰 검증과 인증 여부

### ISSUE THREAD

**Issue by jeeheaG** [RUSH-1472/rush-logistic-system-2024#2]
원래는 엔드포인트 별로 권한에 따른 접근제한을 gateway 에서 해주려고 생각했었는데,
어차피 각 서비스에서 확인해야 하는 부분들이 있고(해당 주문의 담당자인지 등)
gateway 에서 모든 엔트포인트를 관리하기가 쉽지 않을 것 같아서
gateway 에서는 토큰 유효 여부 정도만 검증한 후 토큰이나 useId 값을 전달해주면 어떨까 생각해보았습니다.
각 서비스에서 security 를 사용하거나 직접 처리해도 될 것 같아요!
코멘트로 의견 부탁드립니다~

**Comment by Hany-Kim** [comment]
저도 과제하면서 gateway에서 접근권한 처리하면서 각 서비스 담당자가 gateway에서 권한 처리한다면 비효율적이고 가독성도 떨어질거 같아 고민해봤는데, 이번엔 의견주신대로 해봐야겠습니다.

**Comment by wkdehf217** [comment]
좋은생각인거 같습니다! 저번에 과제할때 gateway 에서 userId, Role만 넘겨서 해봤었는데 편하더라구요. 
넘긴 값으로 각 서비스에서 사용하면 될거같습니다.

**Comment by Hxxseung** [comment]
권한검증까지 Gateway에서 처리하면 Gateway에서의 부하가 집중될 것 같아서 제안 주신 아이디어가 좋을 것 같습니다

**Comment by jeeheaG** [comment]
네 gateway 에서 userId, role 값 추출해서 그것만 해당 서비스에 전달하는 걸로 하겠습니다!
다들 의견 감사합니다.
